#+TITLE: Bayus
#+AUTHOR: Sn4red
#+EMAIL: joaquin.arriaga08@gmail.com
#+DESCRIPTION: README for Bayus on GitHub
#+LANGUAGE: en

[[https://img.shields.io/badge/javascript-%23323330.svg?style=for-the-badge&logo=javascript&logoColor=%23F7DF1E]]
[[https://img.shields.io/badge/node.js-6DA55F.svg?style=for-the-badge&logo=node.js&logoColor=white]]
[[https://img.shields.io/badge/Discord-%235865F2.svg?style=for-the-badge&logo=discord&logoColor=white]]
[[https://img.shields.io/badge/firebase-a08021.svg?style=for-the-badge&logo=firebase&logoColor=ffcd34]]

Bayus is a Discord bot that assists with the administration of The Bunk3r
server.

* Table of Contents
- [[#information][Information]]
- [[#backup][Backup]]
- [[#emojis][Emojis]]
- [[#scp][SCP]]
- [[#events][Events]]

* Information
~/channels~, ~/information~ and ~/rules~ provide containers with information and
server rules, and are only posted in the information channels. Also,
~/braindump~ is a personal-use command that displays quick-access buttons with
useful links.

* Backup
~/backup~ provides administrative tools to create, query, upload, and delete
backups for a particular server:

- ~/backup~ ~create~: creates a full server backup in a ~JSON~ file, including
  channels, roles, emojis, and up to 10 messages per channel.
- ~/backup~ ~information~: displays the details of an existing backup, showing
  the ID, server, size, and creation date.
- ~/backup~ ~load~: loads a backup onto a server, deleting its current structure
  and completely replacing it with the one from the backup.
- ~/backup~ ~delete~: permanently deletes an existing backup using its ID.

* Emojis
Bayus has commands to copy emojis from one server to another, and to copy all
emojis from a given server, save them in a ~JSON~ file to be able to load
them into another server:

- ~/stealemoji~: gets the emoji from a string option and creates a URL to
  obtain the source. Then, the new emoji is uploaded to the server with a
  given name.
- ~/transferemojis~ ~copy~: stores the URL and name of all emojis from the server
  where it's executed into a ~JSON~ file.
- ~/transferemojis~ ~paste~: uploads the emojis from the ~JSON~ file to the
  server where it's executed, using the URL to fetch the source, and the name
  to create the new emoji ID. The Discord API only allows uploading 50 emojis
  per hour, so the execution process may take a considerable amount of time.

* SCP
As a support bot for The Bunk3r, Bayus has commands related to [[https://github.com/Sn4red/SCP-Collector][SCP Collector]]
process:

- ~/countcards~: counts how many SCP cards (documents) are currently stored in
  the Firestore database.
- ~/seecard~: retrieves and displays an SCP card by its ID, pulling the data
  directly from Firestore.
- ~/uploadcards~: Parses and uploads SCP card JSON files-each representing a
  single class-to the Firestore database, one by one.

* Events
- Leveraging the ~ClientReady~ event, Bayus fetches the number of server
  members with the ~Member~ role and updates a voice channel name with the
  count every 10 minutes.
- When a new member joins the server, Bayus automatically assigns them the
  ~Member~ role via the ~GuildMemberAdd~ event and sends a personalized welcome
  card to a text channel using ~@napi-rs/canvas~.
